### ISSUE TITLE
Budget Treemap visualization

### ISSUE THREAD

**Issue by ajturner** [ajturner/dc-council#12]

**Comment by ajturner** [comment]
I couldn't make it to the holiday party - so instead I added a beta treemap budget visualization

https://user-images.githubusercontent.com/1218/208016748-625f6ef9-77f8-4ae9-9782-f221bdc735a4.mov

![Image](https://user-images.githubusercontent.com/1218/208016375-3beda841-18f0-4dc5-a6fb-10e6261e2680.png)



@NSementelli

**Comment by NSementelli** [comment]
That's one way to celebrate, lol
