### ISSUE TITLE
Add "Other Agencies" option in agency left-hand list that allows drop down of our secondary excel sheet. If chosen, it should replace itself in the list so you can choose it multiple times

### ISSUE THREAD

**Issue by ajturner** [ajturner/dc-council#3]

**Comment by ajturner** [comment]
@NSementelli this feature has been added & deployed! Please let me know any feedback



![Image](https://user-images.githubusercontent.com/1218/205077577-262b2181-1690-4334-a12e-340a69a69104.png)

**Comment by NSementelli** [comment]
awesome. i'm going to write the post this weekend so we can get this
published early next week.

**Comment by ajturner** [comment]
great - I'll keep making updates, hopefully fixing social media sharing too
